{
 "title": "Kafka Streams Spring",
 "description": "Dashboard for a Kafka Streams Spring applications using Prometheus JMX-Exporter",
 "tags": [
  "Kafka Streams",
  "Prometheus",
  "Kubernetes",
  "Streams",
  "Kafka"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Node Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Running Instances",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(count by (application_id) (kafka_streams_stream_metrics{job=\"kafka-streams\", application_id!=\"\"}))"
    }
   ]
  },
  {
   "title": "Currently Running Tasks",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_streams_stream_thread_metrics_task_created_total) - sum(kafka_streams_stream_thread_metrics_task_closed_total)",
     "legendFormat": "Running Tasks"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - container_start_time_seconds{name=~\".*-stream-.*\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes", "label": "bytes (SI)" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name=~\".*-stream-.*\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{name=~\".*-stream-.*\"}[5m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Streams Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {}
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kafka_streams_stream_thread_metrics_process_total{job=\"kafka-streams\"})",
     "legendFormat": "Processed Records"
    },
    {
     "expr": "sum(kafka_streams_stream_thread_metrics_poll_total{job=\"kafka-streams\"})",
     "legendFormat": "Polls"
    },
    {
     "expr": "sum(kafka_streams_stream_thread_metrics_commit_total{job=\"kafka-streams\"})",
     "legendFormat": "Commits"
    },
    {
     "expr": "sum(kafka_streams_stream_thread_metrics_task_created_total{job=\"kafka-streams\"})",
     "legendFormat": "Created Tasks"
    }
   ]
  },
  {
   "title": "Consumer Lag",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "none", "label": "records" }
   ],
   "targets": [
    {
     "expr": "label_replace(kafka_consumer_consumer_fetch_manager_metrics_records_lag_avg{job=\"kafka-streams\"}, \"hostname\", \"$1\", \"hostname\", \"(.*).mycompany.com\")",
     "legendFormat": "{{hostname}} -> {{topic}}"
    }
   ]
  },
  {
   "title": "Records Processed (K recs)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(kafka_streams_stream_thread_metrics_process_total{job=\"kafka-streams\"}/1000, \"hostname\", \"$1\", \"hostname\", \"(.*).mycompany.com\")",
     "legendFormat": "{{hostname}} "
    }
   ]
  },
  {
   "title": "Record E2E Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "label_replace(max(kafka_streams_stream_processor_node_metrics_record_e2e_latency_max >= 0) by (thead_id,hostname), \"hostname\", \"$1\", \"hostname\", \"(.*).mycompany.com\")",
     "legendFormat": "{{hostname}} max"
    },
    {
     "expr": "label_replace(min(kafka_streams_stream_processor_node_metrics_record_e2e_latency_min >= 0) by (thead_id,hostname), \"hostname\", \"$1\", \"hostname\", \"(.*).mycompany.com\")",
     "legendFormat": "{{hostname}} min"
    }
   ]
  },
  {
   "title": "Poll Records Per Poll",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(kafka_streams_stream_thread_metrics_poll_records_avg, \"hostname\", \"$1\", \"hostname\", \"(.*).mycompany.com\")",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Average Process Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "label_replace(kafka_streams_stream_thread_metrics_process_latency_avg, \"hostname\", \"$1\", \"hostname\", \"(.*).mycompany.com\")",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Process Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "none", "label": "records/sec" }
   ],
   "targets": [
    {
     "expr": "label_replace(kafka_streams_stream_thread_metrics_process_rate, \"hostname\", \"$1\", \"hostname\", \"(.*).mycompany.com\")",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Average Poll Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "label_replace(kafka_streams_stream_thread_metrics_poll_latency_avg, \"hostname\", \"$1\", \"hostname\", \"(.*).mycompany.com\")",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Poll Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "none", "label": "polls/sec" }
   ],
   "targets": [
    {
     "expr": "label_replace(kafka_streams_stream_thread_metrics_poll_rate, \"hostname\", \"$1\", \"hostname\", \"(.*).mycompany.com\")",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Commit Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "label_replace(kafka_streams_stream_thread_metrics_commit_latency_avg, \"hostname\", \"$1\", \"hostname\", \"(.*).mycompany.com\")",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Commit Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "yaxes": [
    { "format": "ops", "label": "commits/sec" }
   ],
   "targets": [
    {
     "expr": "label_replace(kafka_streams_stream_thread_metrics_commit_rate, \"hostname\", \"$1\", \"hostname\", \"(.*).mycompany.com\")",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Record Lateness (Out-Of-Order)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "none", "label": "records" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum(kafka_streams_stream_task_metrics_record_lateness_avg > 0) by (hostname), \"hostname\", \"$1\", \"hostname\", \"(.*).mycompany.com\")",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  { "title": "RocksDB", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 } },
  {
   "title": "Get Rate (ops/sec)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
   "yaxes": [
    { "format": "none", "label": "gets/sec" }
   ],
   "targets": [
    {
     "expr": "label_replace(avg(kafka_streams_stream_state_metrics_get_rate) by (hostname), \"hostname\", \"$1\", \"hostname\", \"(.*).mycompany.com\")",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Get Avg Latency (ms)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "label_replace(avg(kafka_streams_stream_state_metrics_get_latency_avg >= 0) by (hostname), \"hostname\", \"$1\", \"hostname\", \"(.*).mycompany.com\")",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Put Rate (ops/sec)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
   "yaxes": [
    { "format": "none", "label": "puts/sec" }
   ],
   "targets": [
    {
     "expr": "label_replace(avg(kafka_streams_stream_state_metrics_put_rate) by (hostname), \"hostname\", \"$1\", \"hostname\", \"(.*).mycompany.com\")",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Put Avg Latency (ms)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 82 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "label_replace(avg(kafka_streams_stream_state_metrics_put_latency_avg >= 0) by (hostname), \"hostname\", \"$1\", \"hostname\", \"(.*).mycompany.com\")",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Block Cache Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 90 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "label_replace(max(kafka_streams_stream_state_metrics_block_cache_capacity) by (hostname,rocksdb_state_id), \"hostname\", \"$1\", \"hostname\", \"(.*).mycompany.com\")",
     "legendFormat": "{{hostname}} {{rocksdb_state_id}} Capacity"
    },
    {
     "expr": "label_replace(max(kafka_streams_stream_state_metrics_block_cache_usage) by (hostname,rocksdb_state_id), \"hostname\", \"$1\", \"hostname\", \"(.*).mycompany.com\")",
     "legendFormat": "{{hostname}} {{rocksdb_state_id}} Used"
    }
   ]
  },
  {
   "title": "Record Cache Hit Ratio",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 90 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "label_replace(avg(kafka_streams_stream_record_cache_metrics_hit_ratio_avg >= 0) by (hostname,rocksdb_state_id), \"hostname\", \"$1\", \"hostname\", \"(.*).mycompany.com\")",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Total Size of All Memtables",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 98 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum(kafka_streams_stream_state_metrics_size_all_mem_tables >= 0) by (hostname,rocksdb_state_id), \"hostname\", \"$1\", \"hostname\", \"(.*).mycompany.com\")",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Size of Live SST Files",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 98 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum(kafka_streams_stream_state_metrics_live_sst_files_size >= 0) by (hostname,rocksdb_state_id), \"hostname\", \"$1\", \"hostname\", \"(.*).mycompany.com\")",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Memory for Reading SSTs (Excludes Block Cache)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 106 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum(kafka_streams_stream_state_metrics_estimate_table_readers_mem >= 0) by (hostname,rocksdb_state_id), \"hostname\", \"$1\", \"hostname\", \"(.*).mycompany.com\")",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Memory for Entries Pinned in Block Cache",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 106 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum(kafka_streams_stream_state_metrics_block_cache_pinned_usage >= 0) by (hostname,rocksdb_state_id), \"hostname\", \"$1\", \"hostname\", \"(.*).mycompany.com\")",
     "legendFormat": "{{hostname}}"
    }
   ]
  }
 ]
}