{
 "title": "Kafka Streams",
 "description": "Dashboard for a Kafka Streams application using Prometheus JMX-Exporter running in Kubernetes",
 "tags": [
  "Kafka Streams",
  "Prometheus",
  "Kubernetes",
  "Streams",
  "Kafka"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Node Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Running Instances",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(kafka_streams_application_id)"
    }
   ]
  },
  {
   "title": "Currently Running Tasks",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_streams_task_created_total) - sum(kafka_streams_task_closed_total)",
     "legendFormat": "Running Tasks"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - container_start_time_seconds{name=~\".*-stream-.*\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes", "label": "bytes (SI)" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name=~\".*-stream-.*\"}/(1024*1024)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{name=~\".*-stream-.*\"}[5m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Streams Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {}
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kafka_streams_process_total{hostname=~\".*-stream-.*\"})",
     "legendFormat": "Processed Records"
    },
    {
     "expr": "sum(kafka_streams_poll_total{hostname=~\".*-stream-.*\"})",
     "legendFormat": "Polls"
    },
    {
     "expr": "sum(kafka_streams_commit_total{hostname=~\".*-stream-.*\"})",
     "legendFormat": "Commits"
    },
    {
     "expr": "sum(kafka_streams_task_created_total{hostname=~\".*-stream-.*\"})",
     "legendFormat": "Created Tasks"
    }
   ]
  },
  {
   "title": "Consumer Lag",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "none", "label": "records" }
   ],
   "targets": [
    {
     "expr": "kafka_streams_records_lag_avg_records",
     "legendFormat": "{{hostname}} -> {{topic}}"
    }
   ]
  },
  {
   "title": "Records Processed (K recs)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_streams_process_total/1000",
     "legendFormat": "{{hostname}} "
    }
   ]
  },
  {
   "title": "Record E2E Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "max(kafka_streams_record_e2e_latency_max)",
     "legendFormat": "Max Record E2E Latency"
    },
    {
     "expr": "min(kafka_streams_record_e2e_latency_min)",
     "legendFormat": "Min Record E2E Latency"
    }
   ]
  },
  {
   "title": "Poll Records",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kafka_streams_poll_rate", "legendFormat": "{{hostname}}" },
    {
     "expr": "avg(kafka_streams_poll_records_avg)",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Process Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "max(kafka_streams_process_latency_max)",
     "legendFormat": "Max Process Latency"
    },
    {
     "expr": "avg(kafka_streams_process_latency_avg)",
     "legendFormat": "Avg Process Latency"
    }
   ]
  },
  {
   "title": "Process Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "none", "label": "records/sec" }
   ],
   "targets": [
    { "expr": "kafka_streams_process_rate", "legendFormat": "{{hostname}}" }
   ]
  },
  {
   "title": "Poll Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "max(kafka_streams_poll_latency_max)",
     "legendFormat": "Max Thread Poll Latency"
    },
    {
     "expr": "avg(kafka_streams_poll_latency_avg)",
     "legendFormat": "Avg Thread Poll Latency"
    }
   ]
  },
  {
   "title": "Poll Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "none", "label": "polls/sec" }
   ],
   "targets": [
    { "expr": "kafka_streams_poll_rate", "legendFormat": "{{hostname}}" }
   ]
  },
  {
   "title": "Commit Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "max(kafka_streams_commit_latency_max_seconds)",
     "legendFormat": "Max Thread Commit Latency"
    },
    {
     "expr": "avg(kafka_streams_commit_latency_avg_seconds)",
     "legendFormat": "Avg Thread Commit Latency"
    }
   ]
  },
  {
   "title": "Commit Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "yaxes": [
    { "format": "ops", "label": "commits/sec" }
   ],
   "targets": [
    {
     "expr": "kafka_streams_commit_rate_commits",
     "legendFormat": "{{hostname}}"
    }
   ]
  }
 ]
}