{
 "title": "Kafka Streams Micronaut",
 "description": "Dashboard for a Kafka Streams Micronaut applications",
 "tags": [
  "Kafka Streams",
  "Prometheus",
  "Kubernetes",
  "Streams",
  "Kafka"
 ],
 "time": { "from": "2023-03-23T16:15:42.460Z", "to": "2023-03-23T18:08:42.460Z" },
 "panels": [
  {
   "title": "Node Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Running Instances",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(kafka_streams_application_id)"
    }
   ]
  },
  {
   "title": "Currently Running Tasks",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_streams_task_created_total) - sum(kafka_streams_task_closed_total)",
     "legendFormat": "Running Tasks"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - container_start_time_seconds{name=~\".*-stream-.*\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "CPU Usage by Container",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{name=~\".*-stream-.*\"}[5m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Usage by Container",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes", "label": "bytes (SI)" }
   ],
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{name=~\".*-stream-.*\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "CPU Usage by Service Type",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum(label_replace(rate(container_cpu_usage_seconds_total{name=~\".*-stream-.*\"}[5m]), \"name\", \"$1\", \"name\", \"(.*)-stream-[0-9]*\")) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Usage by Service Type",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes", "label": "bytes (SI)" }
   ],
   "targets": [
    {
     "expr": "sum(label_replace(container_memory_working_set_bytes{name=~\".*-stream-.*\"}, \"name\", \"$1\", \"name\", \"(.*)-stream-[0-9]*\")) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory in Page Cache",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "decbytes", "label": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name=~\".*-stream-.*\"}-container_memory_working_set_bytes{name=~\".*-stream-.*\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "decbytes", "label": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_fs_usage_bytes{name=~\".*-stream-.*\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Streams Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {}
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kafka_streams_process_total{hostname=~\".*-stream-.*\"})",
     "legendFormat": "Processed Records"
    },
    {
     "expr": "sum(kafka_streams_poll_total{hostname=~\".*-stream-.*\"})",
     "legendFormat": "Polls"
    },
    {
     "expr": "sum(kafka_streams_commit_total{hostname=~\".*-stream-.*\"})",
     "legendFormat": "Commits"
    },
    {
     "expr": "sum(kafka_streams_task_created_total{hostname=~\".*-stream-.*\"})",
     "legendFormat": "Created Tasks"
    }
   ]
  },
  {
   "title": "Consumer Lag",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "none", "label": "records" }
   ],
   "targets": [
    {
     "expr": "label_replace(kafka_streams_records_lag_avg_records, \"hostname\", \"$1\", \"hostname\", \"(.*).mycompany.com\")",
     "legendFormat": "{{hostname}} -> {{topic}}"
    }
   ]
  },
  {
   "title": "Records Processed (K recs)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(label_replace(kafka_streams_process_total{hostname=~\".*-stream-.*\"}, \"hostname\", \"$1\", \"hostname\", \"(.*)-stream-[0-9]*.mycompany.com\")) by (hostname)/1000",
     "legendFormat": "{{hostname}} "
    }
   ]
  },
  {
   "title": "Records Processed per Record Type",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "none", "label": "K records" }
   ],
   "targets": [
    {
     "expr": "sum(label_replace(kafka_streams_process_total{hostname=~\".*-stream-.*\"}, \"hostname\", \"$1\", \"hostname\", \"(.*)-stream-[0-9]*.mycompany.com\")) by (hostname)/1000",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Process Rate by Service Type",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "none", "label": "records/sec" }
   ],
   "targets": [
    {
     "expr": "sum(label_replace(kafka_streams_process_rate{hostname=~\".*-stream-.*\"}, \"hostname\", \"$1\", \"hostname\", \"(.*)-stream-[0-9]*.mycompany.com\")) by (hostname)",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Record E2E Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "max(kafka_streams_record_e2e_latency_max)",
     "legendFormat": "Max Record E2E Latency"
    },
    {
     "expr": "min(kafka_streams_record_e2e_latency_min)",
     "legendFormat": "Min Record E2E Latency"
    }
   ]
  },
  {
   "title": "Poll Records",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(kafka_streams_poll_rate, \"hostname\", \"$1\", \"hostname\", \"(.*).mycompany.com\")",
     "legendFormat": "{{hostname}}"
    },
    {
     "expr": "avg(kafka_streams_poll_records_avg)",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Process Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "max(kafka_streams_process_latency_max)",
     "legendFormat": "Max Process Latency"
    },
    {
     "expr": "avg(kafka_streams_process_latency_avg)",
     "legendFormat": "Avg Process Latency"
    }
   ]
  },
  {
   "title": "Poll Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "yaxes": [
    { "format": "none", "label": "polls/sec" }
   ],
   "targets": [
    {
     "expr": "label_replace(kafka_streams_poll_rate, \"hostname\", \"$1\", \"hostname\", \"(.*).mycompany.com\")",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Poll Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "max(kafka_streams_poll_latency_max)",
     "legendFormat": "Max Thread Poll Latency"
    },
    {
     "expr": "avg(kafka_streams_poll_latency_avg)",
     "legendFormat": "Avg Thread Poll Latency"
    }
   ]
  },
  {
   "title": "Commit Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "yaxes": [
    { "format": "ops", "label": "commits/sec" }
   ],
   "targets": [
    {
     "expr": "label_replace(kafka_streams_commit_rate_commits, \"hostname\", \"$1\", \"hostname\", \"(.*).mycompany.com\")",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Commit Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "max(kafka_streams_commit_latency_max_seconds)",
     "legendFormat": "Max Thread Commit Latency"
    },
    {
     "expr": "avg(kafka_streams_commit_latency_avg_seconds)",
     "legendFormat": "Avg Thread Commit Latency"
    }
   ]
  },
  {
   "title": "Average Batch Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 81 },
   "yaxes": [
    { "format": "decbytes", "label": "bytes" }
   ],
   "targets": [
    {
     "expr": "label_replace(avg(kafka_streams_batch_size_avg) by (hostname), \"hostname\", \"$1\", \"hostname\", \"(.*).mycompany.com\")",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Record Lateness (Out-Of-Order)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 89 },
   "yaxes": [
    { "format": "none", "label": "records" }
   ],
   "targets": [
    {
     "expr": "label_replace(kafka_streams_record_lateness_avg, \"hostname\", \"$1\", \"hostname\", \"(.*).mycompany.com\")",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  { "title": "RocksDB", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 97 } },
  {
   "title": "Get Rate (ops/sec)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 98 },
   "yaxes": [
    { "format": "none", "label": "gets/sec" }
   ],
   "targets": [
    {
     "expr": "label_replace(kafka_streams_get_rate, \"hostname\", \"$1\", \"hostname\", \"(.*).mycompany.com\")",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Get Avg Latency (ms)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 98 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "label_replace(kafka_streams_get_latency_avg, \"hostname\", \"$1\", \"hostname\", \"(.*).mycompany.com\")",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Put Rate (ops/sec)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 106 },
   "yaxes": [
    { "format": "none", "label": "puts/sec" }
   ],
   "targets": [
    {
     "expr": "label_replace(kafka_streams_put_rate, \"hostname\", \"$1\", \"hostname\", \"(.*).mycompany.com\")",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Put Avg Latency (ms)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 106 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "label_replace(kafka_streams_put_rate, \"hostname\", \"$1\", \"hostname\", \"(.*).mycompany.com\")",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Block Cache Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 114 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "label_replace(kafka_streams_block_cache_capacity, \"hostname\", \"$1\", \"hostname\", \"(.*).mycompany.com\")",
     "legendFormat": "{{hostname}} Capacity"
    },
    {
     "expr": "label_replace(kafka_streams_block_cache_usage, \"hostname\", \"$1\", \"hostname\", \"(.*).mycompany.com\")",
     "legendFormat": "{{hostname}} Used"
    }
   ]
  },
  {
   "title": "Record Cache Hit Ratio",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 114 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "label_replace(kafka_streams_hit_ratio_avg, \"hostname\", \"$1\", \"hostname\", \"(.*).mycompany.com\")",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Total Size of All Memtables",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 122 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "label_replace(kafka_streams_size_all_mem_tables, \"hostname\", \"$1\", \"hostname\", \"(.*).mycompany.com\")",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Size of Live SST Files",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 122 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "label_replace(kafka_streams_live_sst_files_size, \"hostname\", \"$1\", \"hostname\", \"(.*).mycompany.com\")",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Size of All SST Files",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 130 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "label_replace(kafka_streams_total_sst_files_size, \"hostname\", \"$1\", \"hostname\", \"(.*).mycompany.com\")",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Memory for Entries Pinned in Block Cache",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 130 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "label_replace(kafka_streams_block_cache_pinned_usage, \"hostname\", \"$1\", \"hostname\", \"(.*).mycompany.com\")",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Memory for Reading SSTs (Excludes Block Cache)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 138 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "label_replace(kafka_streams_estimate_table_readers_mem, \"hostname\", \"$1\", \"hostname\", \"(.*).mycompany.com\")",
     "legendFormat": "{{hostname}}"
    }
   ]
  }
 ]
}