global:
  # How frequently to scrape targets by default.
  # Default 15s
  scrape_interval: 30s
  # How frequently to evaluate rules.
  # Default 15s
  evaluation_interval: 15s
  # How long until a scrape request times out.
  # Default to 10s.
  # Required because cp-demo is using cpu throttling, so let's leave enough time to fetch the metrics in particular for the first time as it needs to compile all rexps
  scrape_timeout: 30s

rule_files:
  - "alert.rules"

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets:
            - "alertmanager:9093"

scrape_configs:
  - job_name: "cadvisor"
    static_configs:
      - targets:
          - cadvisor.mycompany.com:8080
  - job_name: "prometheus"
    static_configs:
      - targets:
          - prometheus.mycompany.com:9090
  - job_name: "kafka-streams"
    metrics_path: "/prometheus"
    static_configs:
      - targets:
          - account-contact-stream-1.mycompany.com:9010
          - account-contact-stream-2.mycompany.com:9010
          - account-contact-stream-3.mycompany.com:9010
          - account-contact-stream-4.mycompany.com:9010
          - account-stream-1.mycompany.com:9010
          - account-stream-2.mycompany.com:9010
          - account-stream-3.mycompany.com:9010
          - account-stream-4.mycompany.com:9010
          - contact-address-stream-1.mycompany.com:9010
          - contact-address-stream-2.mycompany.com:9010
          - contact-stream-1.mycompany.com:9010
          - contact-stream-2.mycompany.com:9010
          - contact-stream-3.mycompany.com:9010
          - contact-stream-4.mycompany.com:9010
    relabel_configs:
      - source_labels: [__address__]
        target_label: hostname
        regex: '([^:]+)(:[0-9]+)?'
        replacement: '${1}'