version: '3.5'
services:

  ################## KAFKA ##################

  zoo1:
    image: confluentinc/cp-zookeeper:${CONFLUENT_VERSION}
    hostname: zoo1.${DOMAIN}
    container_name: zoo1
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVERS: zoo1.${DOMAIN}:2888:3888
      ZOOKEEPER_LOG4J_ROOT_LOGLEVEL: DEBUG
      KAFKA_OPTS: "-Dzookeeper.4lw.commands.whitelist=*"
      KAFKA_HEAP_OPTS: "-Xms${ZK_HEAP} -Xmx${ZK_HEAP}"
    volumes:
      - ./volumes/zoo-1/data:/var/lib/zookeeper/data
    networks:
      - kafka-network
    healthcheck:
      test: ["CMD", "bash", "-c", "(echo ruok | nc zoo1.${DOMAIN} 2181) | grep -e imok"]
      start_period: 5s
      interval: 20s
      timeout: 10s
      retries: 20

  kafka1:
    image: confluentinc/cp-server:${CONFLUENT_VERSION}
    hostname: kafka1.${DOMAIN}
    container_name: kafka1
    ulimits:
      nofile:
        soft: 82920
        hard: 82920
    links:
      - zoo1
    depends_on:
      zoo1:
        condition: service_healthy
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      # zookeeper
      KAFKA_ZOOKEEPER_CONNECT: zoo1.${DOMAIN}:2181
      KAFKA_ZOOKEEPER_CLIENT_CNXN_SOCKET: org.apache.zookeeper.ClientCnxnSocketNetty
      # listeners
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka1.${DOMAIN}:29092,EXTERNAL://localhost:9092
      KAFKA_LISTENERS: INTERNAL://kafka1.${DOMAIN}:29092,EXTERNAL://kafka1.${DOMAIN}:9092
      KAFKA_SECURITY_PROTOCOL: PLAINTEXT
      KAFKA_CONFLUENT_BALANCER_ENABLE: 'true'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
      # metrics reporter
      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: kafka1:29092
      CONFLUENT_METRICS_REPORTER_SECURITY_PROTOCOL: PLAINTEXT
      # cluster linking
      CONFLUENT_CLUSTER_LINK_METADATA_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_PASSWORD_ENCODER_SECRET: cl-secret
      # logging
      KAFKA_LOG4J_ROOT_LOGLEVEL: INFO
      KAFKA_LOG4J_LOGGERS: kafka.authorizer.logger=INFO
      #KAFKA_OPTS: '-Djavax.net.debug=ssl'
      #KAFKA_JMX_PORT: 9010
      #KAFKA_JMX_HOSTNAME: localhost
      KAFKA_HEAP_OPTS: "-Xms${BROKER_HEAP} -Xmx${BROKER_HEAP}"
    volumes:
      - ./volumes/kafka-1/data:/var/lib/kafka/data
    networks:
      - kafka-network
    healthcheck:
      test: ["CMD", "bash", "-c", "kafka-cluster cluster-id --bootstrap-server kafka1.${DOMAIN}:29092 | grep -e 'Cluster ID: .*'"]
      start_period: 30s
      interval: 10s
      timeout: 10s
      retries: 10

  schema1:
    image: confluentinc/cp-schema-registry:${CONFLUENT_VERSION}
    hostname: schema1.${DOMAIN}
    container_name: schema1
    links:
      - kafka1
    depends_on:
      kafka1:
        condition: service_healthy
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: 'schema1'
      SCHEMA_REGISTRY_LISTENERS: 'http://0.0.0.0:8081'
      # kafka store
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'PLAINTEXT://kafka1.${DOMAIN}:29092'
      SCHEMA_REGISTRY_KAFKASTORE_SECURITY_PROTOCOL: 'PLAINTEXT'
      SCHEMA_REGISTRY_KAFKASTORE_TOPIC: '_schemas'
      SCHEMA_REGISTRY_KAFKASTORE_ZK_SESSION_TIMEOUT_MS: 60000
      SCHEMA_REGISTRY_KAFKASTORE_TIMEOUT_MS: 10000
      SCHEMA_REGISTRY_KAFKASTORE_INIT_TIMEOUT_MS: 120000
      # other
      SCHEMA_REGISTRY_INTER_INSTANCE_PROTOCOL: 'http'
      SCHEMA_REGISTRY_SCHEMA_REGISTRY_GROUP_ID: 'schema-registry'
      SCHEMA_REGISTRY_LEADER_ELIGIBILITY: 'true'
      SCHEMA_REGISTRY_MODE_MUTABILITY: 'true'
      SCHEMA_REGISTRY_DEBUG: 'true'
      KAFKA_HEAP_OPTS: "-Xms${SCHEMA_HEAP} -Xmx${SCHEMA_HEAP}"
    networks:
      - kafka-network
    healthcheck:
      test: ["CMD", "bash", "-c", "curl http://schema1.${DOMAIN}:8081/subjects"]
      interval: 10s
      timeout: 10s
      retries: 20

  ################## CLIENT ##################

  client:
    image: kafka-client:0.0.1
    build: ./client
    hostname: client.${DOMAIN}
    container_name: client
    links:
      - schema1
    depends_on:
      schema1:
        condition: service_healthy
    command:
      - bash
      - -c
      - |
        touch /tmp/initialized
        tail -f /dev/null
    volumes:
      - ./client/scripts:/scripts
    networks:
      - kafka-network
    healthcheck:
      test: ["CMD", "bash", "-c", "find /tmp/initialized"]
      start_period: 60s
      interval: 15s
      timeout: 15s
      retries: 30

  ################## DATABASE ##################

  postgres:
    image: postgres:latest
    hostname: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: cda
      POSTGRES_USER: kafka-connect-user
      POSTGRES_PASSWORD: K@fk@Conn3ct!
    networks:
      - kafka-network

  ################## CLIENTS ##################

#  producer:
#    image: com.mycompany/kafka-producer:1.0-SNAPSHOT
#    hostname: producer
#    container_name: producer
#    links:
#      - schema1
#    depends_on:
#      schema1:
#        condition: service_healthy
#    ports:
#      - "8800:8080"
#    environment:
#      ACCOUNT_CONTACT_TOPIC: source.accountcontact
#      ACCOUNT_TOPIC: source.account
#      ACCOUNTS: 100000
#      ADDRESSES_PER_CONTACT: 2
#      BATCH_SIZE: 100
#      BOOTSTRAP_URL: kafka1:29092
#      CLIENT_ID: producer
#      CONTACT_ADDRESS_TOPIC: source.contactaddress
#      CONTACT_ROLE_TOPIC: source.contactrole
#      CONTACT_TOPIC: source.contact
#      CONTACTS_PER_ACCOUNT: 3
#      COUNTRY_TOPIC: source.country
#      FREQUENCY_MS: 100
#      PARTITIONS: 5
#      SCHEMA_URL: http://schema1:8081
#      SCHEMAS_PATH: schemas/source
#      STATE_TOPIC: source.state
#      THREADS: 5
#    volumes:
#      - ./volumes/producer/schemas:/schemas
#    networks:
#      - kafka-network
#    healthcheck:
#      test: ["CMD", "sh", "-c", "wget -q -O - http://localhost:8080/health | grep -e '\"status\":\"UP\"'"]
#      interval: 2s
#      timeout: 10s
#      retries: 10
#
#  contact-address-stream:
#    image: com.mycompany/contact-address-stream:1.0-SNAPSHOT
#    hostname: contact-address-stream
#    container_name: contact-address-stream
#    links:
#      - schema1
#    depends_on:
#      schema1:
#        condition: service_healthy
#    ports:
#      - "8800:8080"
#    environment:
#      APP_ID: contact-address-stream
#      BOOTSTRAP_URL: kafka1:29092
#      CLIENT_ID: producer
#      CONTACT_ADDRESS_TOPIC: source.contactaddress
#      COUNTRY_TOPIC: source.country
#      ERROR_TOPIC: error.contactaddress
#      GROUP_ID: contact-address-stream
#      IN_MEMORY_STATE: false
#      OUTPUT_TOPIC: canonical.contactaddress
#      SCHEMA_URL: http://schema1:8081
#      STATE_DIR: /data
#      STATE_STORE_CLEANUP: false
#      STATE_TOPIC: source.state
#      THREADS: 5
#    volumes:
#      - ./volumes/contact-address-stream/data:/data
#    networks:
#      - kafka-network
#    healthcheck:
#      test: ["CMD", "sh", "-c", "wget -q -O - http://localhost:8080/health | grep -e '\"status\":\"UP\"'"]
#      interval: 2s
#      timeout: 10s
#      retries: 10
#
#  consumer:
#    image: com.mycompany/kafka-consumer:1.0-SNAPSHOT
#    hostname: consumer
#    container_name: consumer
#    links:
#      - schema1
#    depends_on:
#      schema1:
#        condition: service_healthy
#    ports:
#      - "8802:8080"
#    environment:
#      BOOTSTRAP_URL: kafka1:29092
#      CLIENT_ID: kafka-consumer
#      COMMIT_TIMEOUT_SECS: 5
#      GROUP_ID: kafka-consumer
#      OFFSET_DAYS: 1
#      POLL_TIMEOUT_SECS: 5
#      SCHEMA_URL: http://schema1:8081
#      TOPIC: customer.transformed
#    networks:
#      - kafka-network
#    healthcheck:
#      test: ["CMD", "sh", "-c", "wget -q -O - http://localhost:8080/health | grep -e '\"status\":\"UP\"'"]
#      interval: 2s
#      timeout: 10s
#      retries: 10

  ################## MONITORING ##################

  redis:
    image: redis:latest
    hostname: redis
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - kafka-network

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    hostname: cadvisor
    container_name: cadvisor
    depends_on:
      - redis
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - kafka-network

  prometheus:
    image: ubuntu/prometheus
    hostname: prometheus
    container_name: prometheus
    depends_on:
      - cadvisor
    ports:
      - "9090:9090/tcp"
    environment:
      DOMAIN: ${DOMAIN}
    volumes:
      - ./volumes/prometheus:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - kafka-network

  grafana:
    image: grafana/grafana
    hostname: grafana
    container_name: grafana
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    environment:
      DOMAIN: ${DOMAIN}
      # Disable login for Grafana
      GF_AUTH_DISABLE_LOGIN_FORM: 'true'
      GF_AUTH_ANONYMOUS_ENABLED: 'true'
      GF_AUTH_ANONYMOUS_ORG_ROLE: 'Admin'
      GF_USERS_ALLOW_SIGN_UP: 'false'
    volumes:
      - ./volumes/grafana/data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/dashboards:/etc/grafana/dashboards
    networks:
      - kafka-network
networks:
  kafka-network:
    name: ${DOMAIN}